services:
    tripwer.accounts.forms.member_registration:
        class: Tripwer\AccountsBundle\Form\MemberRegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tripwer_member_registration }