services:
    tripwer.accounts.forms.user_registration:
        class: Tripwer\AccountsBundle\Form\UserRegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tripwer_user_registration }